server:
  port: 8080
  error:
    include-stacktrace: on_param


spring:
  application:
    name: bank-transactions


logging:
  level:
      org.springframework.web: trace

  info:
    env:
      enabled: true

info:
  app: Bank transactions by user
  github: https://github.com/MatheusRdk/
